name: Flutter Android CI/CD

on:
  push:
    branches: [ master ]  # Only triggers on master branch

env:
  FLUTTER_VERSION: "3.29.3"  # Update to latest stable version

jobs:
  build-android:
    name: Build Android Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter analyzer
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
